### ISSUE TITLE
How to Import to Anki?

### ISSUE THREAD

**Issue by Cauch-BS** [jeffchiou/obsidiflip#4]
I really appreaciate this code, but I seem to be having a few issues when importing to Anki.
 
I first installed the Obsidian to Anki Plugin and set up the Anki Addon Anki Connect as described [here](https://github.com/Pseudonium/Obsidian_to_Anki). 

Then I enabled the Curly Cloze Option and the Highlights to Clozes option. 

I also replaced the Obsidian to Anki main.js in the .obsidian/plugins/obsidian-to-anki-plugin with the file at [here](https://github.com/jeffchiou/obsidian-to-anki-patched/releases). 

After completing these steps and others as given in your instructions, the Anki Cards seem to functioning quite well while working "inside" Obsidian. However, I seem to be unable to import these cards to Anki after pressing the "Obsidian to Anki - Scan Vault" button. When I turned on the console, I seemed to be getting an error.  

![image](https://github.com/jeffchiou/obsidiflip/assets/124439247/aa229b70-0f96-4070-9bf1-76b431d769fa)

I would really appreciate it if you could tell me why I seem to be getting this error. 

_This is my first post in github, and I'm not really familiar with this site. However, I wasn't sure where else to post this issue I am having so I'm posting it here._

**Comment by Cauch-BS** [comment]
This is unrelated to the question above but is there any way to modify the given snippet so that instead hovering to flip a card I can click on it?

**Comment by Cauch-BS** [comment]
@jeffchiou

**Comment by jeffchiou** [comment]
Hi @Cauch-BS, apologies for the delay, have been busy and away from home for a couple weeks. If you are ok with clicking and holding to see the back of the card, you can change the css `hover` attributes to `active`.

For example:
```css
.admonition-anki:active .admonition-anki-back {
    transform: rotateX(0deg);
}
.admonition-anki:active .admonition-anki-front {
    transform: rotateX(180deg);
}
```

Does this work for you? To do a true state change (like flip and stay flipped) would require either some JS or some hackiness with checkboxes.

**Comment by MoldyWesh** [comment]
What abt the first error

**Comment by Cauch-BS** [comment]
@MoldyWesh I think I was being an idiot with the first error; I had forgotten to do something in the installation README (I don't recall at this point in time).
